name: CI/CD for Lab2 + Lab3

on:
  push:
    branches:
      - github-actions

permissions:
  contents: read
  packages: write

jobs:

  # ---------------------------
  # 1. CI — build and push Docker
  # ---------------------------

  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/devops/mysite:lab3

  # ---------------------------
  # 2. CD — deploy to VM 
  # ---------------------------

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROXY_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |

            echo "===  systemd static site ==="
            cd /home/vboxuser/myapp

            echo "Fetching new code..."
            git fetch origin
            git reset --hard origin/github-actions

            echo "Restarting systemd service..."
            sudo -n systemctl restart myapp || true

            echo "Checking port 8181..."
            curl -f http://localhost:8181 || echo " systemd site unreachable"

            echo "===  Docker deployment ==="

            IMAGE="ghcr.io/vartanchik12/devops/mysite:lab3"
            CONTAINER="mysite-lab3"

            echo "Pulling image..."
            docker pull $IMAGE

            echo "Stopping old container..."
            docker stop $CONTAINER || true

            echo "Removing old container..."
            docker rm $CONTAINER || true

            echo "Running new container..."
            docker run -d \
              --name $CONTAINER \
              -p 8282:80 \
              --restart=always \
              $IMAGE

            echo "Checking port 8282..."
            curl -f http://localhost:8282 || echo " docker site unreachable"

            echo "=== Deployment COMPLETE ==="

